version: '3.1'
services:
  stats-server:
    build: statistics/stat-service
    image: stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - statistics-db
    environment:
      - spring.datasource.url=jdbc:postgresql://statistics-db:5432/ewmstats
        - spring.datasource.username=test
        - spring.datasource.password=test


  statistics-db:
    image: postgres:14-alpine
    container_name: statistics-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"


