version: '3.1'
services:
  stats-server:
    build: statistics/stat-service
    image: statistics
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - statistics-db
    environment:
      - spring.datasource.url=jdbc:postgresql://statistics-db:5432/ewmstats
      - spring.datasource.username=test
      - spring.datasource.password=test
      - STAT_SERVICE_URL=http://stat-service:9090


  statistics-db:
    image: postgres:14-alpine
    container_name: statistics-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - spring.datasource.url=jdbc:postgresql://ewm-db:5432/ewmmain
      - spring.datasource.username=test
      - spring.datasource.password=test
      - STAT_SERVICE_URL=http://stat-service:9090

  ewm-db:
    image: postgres:15.3-alpine3.18
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewmmain
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test